# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeIOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeIOSApp

  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod "SwiftSpinner"
  pod 'RealmSwift', '=10.1.4'
  pod "PromiseKit", "~> 6.8"
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'KeychainSwift', '~> 19.0'


end
